### ISSUE TITLE
Fail to find hdf5.h file

### ISSUE THREAD

**Issue by frank-stonybrook** [h5md/VMD-h5mdplugin#18]
I edit HDF5LDFLAGS and HDF5CPPFLAGS to the path which I installed hdf5 and run the make. However, I get error message:
gcc h5mdtest.c -o h5mdtest h5mdplugin.c -I/usr/local/lib/vmd/plugins/include  -std=c99 -L /home/frank/HDF5/lib -L  -Wl,-rpath,/home/frank/Documents/VMD-h5mdplugin-master -lhdf5_hl -lhdf5 -lh5md
h5mdplugin.c:21:18: fatal error: hdf5.h: No such file or directory

Actually the hdf5.h is in the path specified by HDF5CPPFLAGS, why gcc complaints that hdf5.h couldn't be find?

Thanks

**Comment by jonaslandsgesell** [comment]
Actually the plugin supports two build systems:
1) the autotools (make)
2) cmake
If you run make you need to adapt (only) the makefile and refer to the correct paths.
The corresponding part where you need to adapt the makefile is the following:
VMDDIR, HDF5LDFLAGS, HDF5CPPFLAGS

**Comment by frank-stonybrook** [comment]
Hi Jonaslandsgesell,

Is there any reason which causes the make failure? Because I already changed the three variables to the correct paths. 
This is part of my Makefile script, I am not sure whether there is any other problem. 
<img width="647" alt="screen shot 2015-10-13 at 17 56 56" src="https://cloud.githubusercontent.com/assets/10855977/10469542/0e12d9c4-71d4-11e5-999f-67b1a29be947.png">

Thanks

**Comment by jonaslandsgesell** [comment]
Hi Frank,
I am not 100% sure wether this will solve the problem but I think in the oritinal version of the makefile ther is a point behind -L in the following line 
LDFLAGS=$(HDF5LDFLAGS) -L.

**Comment by frank-stonybrook** [comment]
Hi Jonaslandsgesell, 
Unfortunately, I still get error when running make. However if I manually copy the hdf5.h file in the current  directory of Makefile, this error is fixed. Any idea why it happens? 

Thanks

**Comment by jonaslandsgesell** [comment]
I think your adapted Makefile does not correctly try to use the header files. Otherwise your gcc command should look like:

gcc h5mdtest.c -o h5mdtest h5mdplugin.c -I/usr/local/lib/vmd/plugins/include -I/ -std=c99 -L /home/frank/HDF5/lib -L -Wl,-rpath,/home/frank/Documents/VMD-h5mdplugin-master -lhdf5_hl -lhdf5 -lh5md

**Comment by frank-stonybrook** [comment]
Hi Jonaslandsgesell,

I just download all files and rerun the make. The error still appears. 

After carefully checking the standard gcc command you provided and my results, I find out that the only difference is '-I/home/frank/HDF5/include'. I look at the original Makefile script on github. I think that this command is encoded by the this line in Makefile:
<img width="921" alt="screen shot 2015-10-13 at 19 53 07" src="https://cloud.githubusercontent.com/assets/10855977/10471461/11f21518-71e4-11e5-84c3-468d639a5880.png">

It seems that there is something which encoded this part '-I/home/frank/HDF5/include' is missing??
Another thing which confirms my suspension is that the variable 'CPPFLAGS' never used after defining. 
Thanks
Frank

**Comment by frank-stonybrook** [comment]
Hi Jonaslandsgesell,

I figure out the problem. There is $(HDF5CPPFLAGS) missing in the command. When I fix it, the make doesn't complain this problem.

**Comment by jonaslandsgesell** [comment]
Thanks for the hint. I will fix this.
