### ISSUE TITLE
/usr/bin/ld: cannot find -lh5md

### ISSUE THREAD

**Issue by frank-stonybrook** [h5md/VMD-h5mdplugin#19]
Hi  Jonaslandsgesell, 

I encountered another problem when I try to run make. 
<img width="939" alt="screen shot 2015-10-13 at 21 34 11" src="https://cloud.githubusercontent.com/assets/10855977/10472752/2d115ada-71f2-11e5-8d9e-911244e40ca6.png">
Then I use command:
ld -lh5md -verbose
to figure out what happened. The output is like this:
<img width="486" alt="screen shot 2015-10-13 at 21 35 35" src="https://cloud.githubusercontent.com/assets/10855977/10472771/5eadf440-71f2-11e5-9b98-1616ba43a06d.png">

It seems that it couldn't find that file in all possible directories. I guess that the libh5md.so or libh5md.a should be somewhere in the HDF5/lib or HDF5/include. However I couldn't find it in either of them. 

Thanks
Frank

**Comment by frank-stonybrook** [comment]
I just find out that the "libh5md.so" file is in the same directory of Makefile, but why it couldn't be find when I run make.

**Comment by jonaslandsgesell** [comment]
The reason for that should be that there is missing a point (for the currently directory) after the lonesome -L

**Comment by frank-stonybrook** [comment]
Thanks! It works now
